"""
.github/workflows/ci.yml
Continuous Integration for Python 3.14
Updated for wxPython dashboard testing
"""

name: Python 3.14 Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.14
      uses: actions/setup-python@v4
      with:
        python-version: "3.14"
    
    - name: Install system dependencies for wxPython
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest ruff mypy
    
    - name: Lint with ruff
      run: ruff check . --target-version py314
    
    - name: Type check with mypy
      run: mypy --python-version 3.14 . --exclude 'dashboard_env|venv_dashboard'
    
    - name: Test imports
      run: |
        python -c "import wx_utils; print('wx_utils OK')"
        python -c "import chart_widgets; print('chart_widgets OK')"
        python -c "import ui_components; print('ui_components OK')"
    
    - name: Run tests
      run: pytest tests/ -v
      if: hashFiles('tests/**/*.py') != ''

  dashboard-validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.14
      uses: actions/setup-python@v4
      with:
        python-version: "3.14"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install plotly pandas numpy wxPython
    
    - name: Validate dashboard modules
      run: |
        python -c "from wx_utils import Colors; print(f'BG_DARK: {Colors.BG_DARK}')"
        python -c "from chart_widgets import MetricCard; print('MetricCard imported')"
        python -c "from ui_components import TradingForm; print('TradingForm imported')"

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.14
      uses: actions/setup-python@v4
      with:
        python-version: "3.14"
    
    - name: Security scan with bandit
      run: |
        pip install bandit
        bandit -r . -ll --exclude './dashboard_env,./venv_dashboard'